version: '3.14'
services:
  back-inventario:
    build:
      context: ./
      dockerfile: backinventario.Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_DB_URI=mongodb+srv://admin:admin@inventario.k32rhkn.mongodb.net/
      - RABBIT_MQ_URI=amqp://rabbitmq-inventory:5672
    links:
      - rabbitmq-inventory
    volumes:
      - command-data:/command/app/data
  persistence:
    build:
      context: ./
      dockerfile: persistence.Dockerfile
    ports:
      - 3002:3002 
    links:
      - mysql-inventory
      - rabbitmq-inventory
    volumes:
      - query-data:/query/app/data
  soketio:
    build:
      context: ./
      dockerfile: soketIo.Dockerfile
    ports:
      - 3001:3001
      - 81:81
    environment:
      - RABBITURL=amqp://rabbitmq-inventory:5672
    links:
      - rabbitmq-inventory
    volumes:
      - socket-data:/query/app/data
    
  mysql-inventory:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inventariotraining
    volumes:
      - mysql-data:/var/lib/mysql
  rabbitmq-inventory:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  command-data:
  query-data:
  socket-data:
  mysql-data:
  rabbitmq-data: